#!/usr/bin/env python3
"""Calibrate one node's OV5647, start to finish, and install the result.

Run this on the node, with the calib.io board in hand. It captures through
rpicam-still, checks each shot for usable corners before you move on, tracks
whether you have covered the frame, runs the existing calibration, and writes
straight to config/camera_calibration.json where co-registration reads it.

    python tools/calibrate_node.py                 # guided capture, then calibrate
    python tools/calibrate_node.py --shots 25
    python tools/calibrate_node.py --from-dir calib_images   # skip capture
    python tools/calibrate_node.py --dry-run       # calibrate, print, install nothing

Why per node
------------
The intrinsics that transfer between units of the same part are the radial
terms. The principal point does not: it encodes how that particular module's
sensor and lens are seated. On the calibration currently shipped, cx and cy sit
24.7 and 39.1 px off centre, and another unit's offset will differ. Borrowing a
sibling's calibration is better than none, but it imports that unit's seating
error into this node's georeferencing.

Getting a good result
---------------------
Vary the pose. Tilt the board, do not keep it flat-on. Move it near and far, and
into all four corners of the frame, not just the middle. Level-only or
same-distance views give a low-looking RMS that is really just an under-
constrained fit. Keep the board rigid and evenly lit, and avoid motion blur.
"""
from __future__ import annotations

import argparse
import datetime
import json
import os
import shutil
import socket
import subprocess
import sys
import tempfile
from pathlib import Path

import cv2
import numpy as np

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(0, str(HERE))

#: The calib.io target in use. 24x17 interior corners, i.e. 25x18 squares.
#: Confirmed twice: a grid sweep against Georeferencing/Calibration Data matched
#: 24x17 and nothing else, and it is what camera_calibration.py declares -- the
#: script that produced the shipped config/camera_calibration.json, which was
#: calibrated on node 007 from Calibration Data/calib_images. Note the printable
#: board generated by tools/generate_calibration_chessboard.py is 9x6 and is a
#: different board; Georeferencing/calibration-checkerboard.py is also set to
#: 9x6 and so cannot detect this target.
BOARD_W, BOARD_H = 24, 17

#: Physical square edge, from SQUARE_SIZE_M in camera_calibration.py, the
#: script that produced the calibration currently shipped in config/. This does
#: NOT affect K or D -- intrinsics are scale free -- it only sets the units of
#: the extrinsics, which matter if the calibration is later used for metric
#: georeferencing. Measure the board and pass --square-mm if it differs.
SQUARE_MM = 30.0

#: Refuse to install worse than this. The shipped calibration achieved 0.278 px.
MAX_RMS_PX = 1.0

#: Minimum usable shots before calibrating at all.
MIN_SHOTS = 12

CONFIG_PATH = REPO / "config" / "camera_calibration.json"


# --------------------------------------------------------------------------- capture
def capture_one(path: Path, width: int, height: int, timeout_ms: int = 2000) -> bool:
    """One still through rpicam-still. libcamera stack, not cv2.VideoCapture."""
    cmd = ["rpicam-still", "-n", "-o", str(path),
           "--width", str(width), "--height", str(height),
           "-t", str(timeout_ms)]
    try:
        r = subprocess.run(cmd, capture_output=True, timeout=60)
    except FileNotFoundError:
        print("rpicam-still not found. This script must run on the node.")
        return False
    except subprocess.TimeoutExpired:
        print("  capture timed out")
        return False
    if r.returncode != 0:
        print(f"  capture failed: {r.stderr.decode()[-200:].strip()}")
        return False
    return path.exists()


def find_corners(img_path: Path, board: tuple[int, int]):
    """Corners if this frame is usable, else None."""
    g = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)
    if g is None:
        return None
    ok, corners = cv2.findChessboardCornersSB(
        g, board, flags=cv2.CALIB_CB_EXHAUSTIVE | cv2.CALIB_CB_ACCURACY)
    if not ok:
        ok, corners = cv2.findChessboardCorners(
            g, board,
            cv2.CALIB_CB_ADAPTIVE_THRESH | cv2.CALIB_CB_NORMALIZE_IMAGE)
    return corners.reshape(-1, 2) if ok else None


def coverage_report(shots: list[np.ndarray], w: int, h: int) -> tuple[str, bool]:
    """Which thirds of the frame the board has actually visited."""
    grid = np.zeros((3, 3), int)
    for c in shots:
        cx, cy = c.mean(0)
        grid[min(2, int(cy / h * 3)), min(2, int(cx / w * 3))] += 1
    filled = int((grid > 0).sum())
    rows = "\n".join("      " + " ".join(f"{n:3d}" for n in r) for r in grid)
    return f"    frame coverage ({filled}/9 cells):\n{rows}", filled >= 6


def guided_capture(out_dir: Path, target: int, board: tuple[int, int],
                   width: int, height: int) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    kept: list[Path] = []
    centres: list[np.ndarray] = []
    print(f"\nCapturing up to {target} usable shots into {out_dir}.")
    print("Move the board between every shot: tilt it, change distance, work the corners.")
    print("Enter to capture, 's' to stop early, 'q' to abort.\n")

    attempt = 0
    while len(kept) < target:
        ans = input(f"  [{len(kept)}/{target} usable] Enter to capture: ").strip().lower()
        if ans == "q":
            print("  aborted"); return []
        if ans == "s":
            break
        attempt += 1
        p = out_dir / f"calib_{attempt:03d}.jpg"
        if not capture_one(p, width, height):
            continue
        corners = find_corners(p, board)
        if corners is None:
            print("    no board found, not kept. Fill more of the frame, hold still, check lighting.")
            p.unlink(missing_ok=True)
            continue
        kept.append(p)
        centres.append(corners)
        span = (corners.max(0) - corners.min(0)) / np.array([width, height])
        print(f"    kept ({span[0]*100:.0f}% x {span[1]*100:.0f}% of frame)")
        if len(kept) % 5 == 0:
            rep, _ = coverage_report(centres, width, height)
            print(rep)

    if centres:
        rep, ok = coverage_report(centres, width, height)
        print("\n" + rep)
        if not ok:
            print("    WARNING: the board stayed in part of the frame. Distortion is estimated")
            print("    from how straight lines bend at the edges, so corners matter most.")
    return kept


# --------------------------------------------------------------------------- main
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--shots", type=int, default=20, help="usable shots to collect (default 20)")
    ap.add_argument("--from-dir", help="skip capture and calibrate this directory of images")
    ap.add_argument("--board", default=f"{BOARD_W}x{BOARD_H}",
                    help=f"interior corners, default {BOARD_W}x{BOARD_H} (the calib.io board)")
    ap.add_argument("--square-mm", type=float, default=SQUARE_MM,
                    help=f"square edge in mm, default {SQUARE_MM:g}; affects extrinsics only, not K or D")
    ap.add_argument("--width", type=int, default=2592)
    ap.add_argument("--height", type=int, default=1944)
    ap.add_argument("--max-rms", type=float, default=MAX_RMS_PX,
                    help=f"refuse to install above this reprojection error (default {MAX_RMS_PX})")
    ap.add_argument("--out", default=str(CONFIG_PATH), help="where to install the calibration")
    ap.add_argument("--keep-images", help="directory to keep the captures in")
    ap.add_argument("--dry-run", action="store_true", help="calibrate and report, install nothing")
    a = ap.parse_args()

    try:
        bw, bh = (int(x) for x in a.board.lower().split("x"))
    except ValueError:
        ap.error(f"--board must look like 24x17, got {a.board!r}")
    board = (bw, bh)

    tmp = None
    if a.from_dir:
        image_dir = Path(a.from_dir)
        if not image_dir.is_dir():
            ap.error(f"not a directory: {image_dir}")
        n = len(list(image_dir.glob("*.jpg")) + list(image_dir.glob("*.png")))
        print(f"Calibrating from {n} images in {image_dir}")
    else:
        if a.keep_images:
            image_dir = Path(a.keep_images)
        else:
            tmp = tempfile.mkdtemp(prefix="calib_")
            image_dir = Path(tmp)
        kept = guided_capture(image_dir, a.shots, board, a.width, a.height)
        if not kept:
            print("No usable captures; nothing to calibrate.")
            return 1
        if len(kept) < MIN_SHOTS:
            print(f"\nOnly {len(kept)} usable shots. {MIN_SHOTS} is the practical minimum; "
                  f"the fit will be under-constrained.")
            if input("Continue anyway? [y/N] ").strip().lower() != "y":
                return 1

    import camera_calibration as CC
    print("\nRunning calibration...")
    try:
        intr = CC.calibrate_camera(
            image_dir=str(image_dir), save_path=os.devnull, show_corners=False,
            board_w=bw, board_h=bh, square_size_m=a.square_mm / 1000.0)
    except Exception as e:                                   # noqa: BLE001
        print(f"Calibration failed: {type(e).__name__}: {e}")
        return 1

    K = np.array(intr.K, float)
    w, h = intr.img_size
    print(f"\n  RMS reprojection error : {intr.rms:.4f} px")
    print(f"  image size             : {w} x {h}")
    print(f"  focal                  : fx {K[0,0]:.1f}  fy {K[1,1]:.1f}")
    print(f"  principal point        : cx {K[0,2]:.1f} ({K[0,2]-w/2:+.1f} from centre), "
          f"cy {K[1,2]:.1f} ({K[1,2]-h/2:+.1f})")

    if intr.rms > a.max_rms:
        print(f"\nNOT INSTALLING: {intr.rms:.4f} px exceeds the {a.max_rms} px limit.")
        print("Recapture with more pose variety: tilt the board, vary distance, reach the corners.")
        return 1

    payload = {
        "K": [list(map(float, r)) for r in intr.K],
        "D": [list(map(float, r)) for r in np.array(intr.D, float).reshape(1, -1)],
        "img_size": [int(w), int(h)],
        "rms": float(intr.rms),
        "camera_height_m": None,
        "node": socket.gethostname(),
        "calibrated": datetime.datetime.now().isoformat(timespec="seconds"),
        "board": {"interior_corners": [bw, bh], "square_mm": a.square_mm,
                  "source": "calib.io"},
        "n_images": len(list(Path(image_dir).glob("*.jpg")) + list(Path(image_dir).glob("*.png"))),
    }

    if a.dry_run:
        print("\n--dry-run, would have written:\n")
        print(json.dumps(payload, indent=2))
        return 0

    out = Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        bak = out.with_suffix(f".json.bak-{datetime.date.today():%Y%m%d}")
        shutil.copy2(out, bak)
        print(f"\n  previous calibration backed up to {bak.name}")
    out.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"  installed to {out}")
    print(f"\nCo-registration will use this on the next capture. Because the optical geometry")
    print(f"has changed, re-seed the transform cache:")
    print(f"  python tools/seed_registration_cache.py --scene <a high-contrast scene> --runs 5")

    if tmp:
        shutil.rmtree(tmp, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
